# Generated by Django 5.0.6 on 2024-05-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateField(verbose_name='Date Published'),
        ),
    ]
